services:
  mysql:
    image: mysql:8.0
    container_name: mysql-soldiers
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: soldiers-db
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql:/app/db
volumes:
  mysql: